[env:coreboard_f401rc_release]
platform = ststm32
board = coreboard_f401rc
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink
build_type = release

monitor_speed = 115200

build_flags =
    -O2
